[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/propiedades"
  to = "/propiedades.html"
  status = 200

[[redirects]]
  from = "/propiedad-*"
  to = "/propiedad-:splat.html"
  status = 200

[build.environment]
  NODE_VERSION = "18" 